// build.rs — runs `vite build` in web-ui/ if available, then generates a
// manifest of the dist/ output so the Rust binary can embed the React UI at
// compile time (no runtime disk dependency). The generated file
// `src/web/_dist_manifest.rs` contains:
//   pub static INDEX_HTML: &str = include_str!("../../web-ui/dist/index.html");
//   pub static ASSETS: &[(&str, &str)] = &[("assets/index-HASH.js", include_str!(...)), ...];
// When npm or dist/ is absent, the manifest references the legacy fallback so
// `cargo build` never fails solely due to missing frontend build.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let web_ui = manifest_dir.join("web-ui");
    let dist = web_ui.join("dist");

    if !web_ui.exists() {
        return;
    }

    println!("cargo:rerun-if-changed=web-ui/index.html");
    println!("cargo:rerun-if-changed=web-ui/src");
    println!("cargo:rerun-if-changed=web-ui/package.json");
    println!("cargo:rerun-if-changed=web-ui/vite.config.ts");
    println!("cargo:rerun-if-changed=web-ui/tailwind.config.ts");

    let npm = which("npm");
    if let Some(npm) = npm {
        let status = Command::new(npm)
            .arg("run")
            .arg("build:fast")
            .current_dir(&web_ui)
            .status();
        match status {
            Ok(s) if s.success() => {
                println!("cargo:warning=web-ui built successfully");
            }
            _ => {
                if dist.exists() {
                    println!("cargo:warning=web-ui build failed; using stale dist/");
                } else {
                    println!("cargo:warning=web-ui build failed and no dist/ present; React UI will fall back to legacy");
                }
            }
        }
    } else if !dist.exists() {
        println!(
            "cargo:warning=npm not found and web-ui/dist missing; React UI falls back to legacy"
        );
    }

    // Generate the manifest. Always emit it so `ui.rs` can `include!` it.
    let manifest_path = manifest_dir.join("src/web/_dist_manifest.rs");
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    out.push_str("// Embeds the Vite build output (web-ui/dist/) into the binary.\n\n");

    let index_html = dist.join("index.html");
    let assets_dir = dist.join("assets");

    if index_html.exists() {
        // index.html — read at compile time via include_str! relative to this
        // generated file's location (src/web/).
        out.push_str(
            "pub static INDEX_HTML: &str = include_str!(\"../../web-ui/dist/index.html\");\n\n",
        );

        // Collect asset files (js/css). Paths are relative to dist/ for serving.
        let mut assets: Vec<(String, String, &'static str)> = Vec::new();
        if assets_dir.exists() {
            if let Ok(entries) = fs::read_dir(&assets_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if !path.is_file() {
                        continue;
                    }
                    let name = path.file_name().unwrap().to_string_lossy().to_string();
                    let rel = format!("assets/{name}");
                    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
                    // include_bytes! works for any binary; include_str! for text.
                    let include_macro = if ext == "js" || ext == "css" {
                        "include_str!"
                    } else {
                        "include_bytes!"
                    };
                    // Safety: path is known at compile time (build.rs ran).
                    // We emit a relative include path from src/web/.
                    let include_path = format!("../../web-ui/dist/assets/{name}");
                    assets.push((rel, include_path, include_macro));
                }
            }
        }
        assets.sort_by(|a, b| a.0.cmp(&b.0));

        out.push_str("pub static ASSETS: &[(&str, AssetContent)] = &[\n");
        for (rel, include_path, include_macro) in &assets {
            // AssetContent is an enum so JS/CSS are &str and others are &[u8].
            if *include_macro == "include_str!" {
                out.push_str(&format!(
                    "    (\"{rel}\", AssetContent::Text({include_macro}(\"{include_path}\"))),\n",
                ));
            } else {
                out.push_str(&format!(
                    "    (\"{rel}\", AssetContent::Binary({include_macro}(\"{include_path}\"))),\n",
                ));
            }
        }
        out.push_str("];\n");
        out.push_str("pub static HAS_DIST: bool = true;\n");
    } else {
        // No dist/ — emit a stub so the binary compiles. The React UI will
        // return 404 and users fall back to /legacy.
        out.push_str("pub static INDEX_HTML: &str = \"\";\n");
        out.push_str("pub static ASSETS: &[(&str, AssetContent)] = &[];\n");
        out.push_str("pub static HAS_DIST: bool = false;\n");
    }

    // Tell Cargo to rerun if dist files change (so edits to the frontend
    // trigger a re-embed). We watch the directory listing via a sentinel.
    println!("cargo:rerun-if-changed=web-ui/dist/index.html");
    println!("cargo:rerun-if-changed=web-ui/dist/assets");

    if let Err(e) = fs::write(&manifest_path, &out) {
        println!("cargo:warning=failed to write _dist_manifest.rs: {e}");
    }
}

fn which(cmd: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(cmd);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}
