// build.rs — generates a manifest of web-ui/dist/ so the Rust binary can embed
// the React UI at compile time (no runtime disk dependency). The generated file
// `src/web/_dist_manifest.rs` contains:
//   pub static INDEX_HTML: &str = include_str!("../../../web-ui/dist/index.html");
//   pub static ASSETS: &[(&str, AssetContent)] = &[("assets/index-HASH.js", ...), ...];
//
// The frontend build itself (`npm run build:fast`) is NOT run here — it is owned
// by package.sh / CI, so `cargo build` never depends on Node and never
// rebuilds dist/ spuriously (which would force this crate to recompile). When
// dist/ is absent the manifest emits a stub so `cargo build` never fails solely
// due to a missing frontend build (React UI returns 503 until dist/ exists).

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let embed = std::env::var_os("CARGO_FEATURE_EMBED_WEB_UI").is_some();
    let web_ui = manifest_dir.join("../../web-ui");
    let dist = web_ui.join("dist");

    if !web_ui.exists() {
        return;
    }

    if embed {
        println!("cargo:rerun-if-changed=web-ui/index.html");
        println!("cargo:rerun-if-changed=web-ui/src");
        println!("cargo:rerun-if-changed=web-ui/package.json");
        println!("cargo:rerun-if-changed=web-ui/vite.config.ts");
        println!("cargo:rerun-if-changed=web-ui/tailwind.config.ts");
        println!("cargo:rerun-if-changed=web-ui/dist/index.html");
        println!("cargo:rerun-if-changed=web-ui/dist/assets");
    }

    // NOTE: the frontend build (`npm run build:fast`) is intentionally NOT run
    // here. It is owned by package.sh / CI so that `cargo build` never
    // depends on a Node toolchain and never rebuilds dist/ spuriously (a
    // spurious rebuild would bump dist mtimes and force this crate to
    // recompile). build.rs only embeds whatever web-ui/dist/ already exists
    // when `embed-web-ui` is enabled; otherwise the binary serves dist/ from disk at runtime.

    // Generate the manifest (content-stable: only rewritten when it would
    // change), so `ui.rs` can `include!` it without needless recompiles.
    let manifest_path = manifest_dir.join("src/_dist_manifest.rs");
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    if embed {
        out.push_str("// Embeds the Vite build output (web-ui/dist/) into the binary.\n\n");
    } else {
        out.push_str("// Dev build: React UI is served from disk (no include_str! embed).\n\n");
    }

    let index_html = dist.join("index.html");
    let assets_dir = dist.join("assets");

    if embed && index_html.exists() {
        // index.html — read at compile time via include_str! relative to this
        // generated file's location (src/web/).
        out.push_str(
            "pub static INDEX_HTML: &str = include_str!(\"../../../web-ui/dist/index.html\");\n\n",
        );

        // Collect asset files (js/css). Paths are relative to dist/ for serving.
        let mut assets: Vec<(String, String, &'static str)> = Vec::new();
        if assets_dir.exists() {
            if let Ok(entries) = fs::read_dir(&assets_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if !path.is_file() {
                        continue;
                    }
                    let name = path.file_name().unwrap().to_string_lossy().to_string();
                    let rel = format!("assets/{name}");
                    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
                    // include_bytes! works for any binary; include_str! for text.
                    let include_macro = if ext == "js" || ext == "css" {
                        "include_str!"
                    } else {
                        "include_bytes!"
                    };
                    // Safety: path is known at compile time (build.rs ran).
                    // We emit a relative include path from src/web/.
                    let include_path = format!("../../../web-ui/dist/assets/{name}");
                    assets.push((rel, include_path, include_macro));
                }
            }
        }
        assets.sort_by(|a, b| a.0.cmp(&b.0));

        out.push_str("pub static ASSETS: &[(&str, AssetContent)] = &[\n");
        for (rel, include_path, include_macro) in &assets {
            // AssetContent is an enum so JS/CSS are &str and others are &[u8].
            if *include_macro == "include_str!" {
                out.push_str(&format!(
                    "    (\"{rel}\", AssetContent::Text({include_macro}(\"{include_path}\"))),\n",
                ));
            } else {
                out.push_str(&format!(
                    "    (\"{rel}\", AssetContent::Binary({include_macro}(\"{include_path}\"))),\n",
                ));
            }
        }
        out.push_str("];\n");
        out.push_str("pub static HAS_DIST: bool = true;\n");
    } else if embed {
        // No dist/ — emit a stub so the binary compiles. React routes return 503.
        println!(
            "cargo:warning=web-ui/dist missing; run `npm run build:fast` in web-ui/ to embed the React UI"
        );
        out.push_str("pub static INDEX_HTML: &str = \"\";\n");
        out.push_str("pub static ASSETS: &[(&str, AssetContent)] = &[];\n");
        out.push_str("pub static HAS_DIST: bool = false;\n");
    } else {
        out.push_str("pub static INDEX_HTML: &str = \"\";\n");
        out.push_str("pub static ASSETS: &[(&str, AssetContent)] = &[];\n");
        out.push_str("pub static HAS_DIST: bool = false;\n");
    }

    // Only rewrite the manifest when its content actually changes, so a
    // build.rs rerun with identical dist/ does NOT bump the file mtime and
    // force a needless recompile of this crate.
    let prev = fs::read_to_string(&manifest_path).unwrap_or_default();
    if out != prev {
        if let Err(e) = fs::write(&manifest_path, &out) {
            println!("cargo:warning=failed to write _dist_manifest.rs: {e}");
        }
    } else {
        println!("cargo:warning=web-ui manifest unchanged; skipping rewrite");
    }
}
