//! React UI routes — serves the Vite-built SPA from `web-ui/dist/` (embedded
//! at compile time via `_dist_manifest.rs`, generated by `build.rs`).
//!
//! When the dist is present, `/` serves the React app and `/assets/*` serves
//! its hashed JS/CSS chunks. When absent (e.g. npm not installed), `/` falls
//! back to a redirect to `/legacy` so the vanilla UI remains usable.

use axum::body::Body;
use axum::extract::Path;
use axum::http::{header, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::Router;

/// Asset content embedded by the build script. Text assets (JS/CSS) are
/// stored as `&str`; binary assets (fonts/images, if any) as `&[u8]`.
pub enum AssetContent {
    Text(&'static str),
    #[allow(dead_code)]
    Binary(&'static [u8]),
}

include!("_dist_manifest.rs");

/// Router for the React UI: `/` (index) + `/assets/{name}` (hashed chunks).
pub fn react_router() -> Router<()> {
    Router::new()
        .route("/", get(react_index))
        .route("/assets/{*name}", get(react_asset))
}

async fn react_index() -> Response {
    if !HAS_DIST || INDEX_HTML.is_empty() {
        // No frontend build available — return a clear error so users know to
        // run `cd web-ui && npm install && npm run build` (or that npm is missing).
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            [(
                header::CONTENT_TYPE,
                HeaderValue::from_static("text/plain; charset=utf-8"),
            )],
            "React UI not built. Run `cd web-ui && npm install && npm run build` then rebuild the binary.",
        )
            .into_response();
    }
    (
        [(
            header::CONTENT_TYPE,
            HeaderValue::from_static("text/html; charset=utf-8"),
        )],
        INDEX_HTML,
    )
        .into_response()
}

async fn react_asset(Path(name): Path<String>) -> Response {
    let key = format!("assets/{name}");
    let asset = ASSETS.iter().find(|(p, _)| *p == key);
    match asset {
        Some((_, AssetContent::Text(body))) => {
            let ct = mime_for(&name);
            (
                [(header::CONTENT_TYPE, HeaderValue::from_static(ct))],
                *body,
            )
                .into_response()
        }
        Some((_, AssetContent::Binary(body))) => {
            let ct = mime_for(&name);
            (
                [(header::CONTENT_TYPE, HeaderValue::from_static(ct))],
                Body::from(*body),
            )
                .into_response()
        }
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn mime_for(name: &str) -> &'static str {
    if name.ends_with(".js") {
        "application/javascript"
    } else if name.ends_with(".css") {
        "text/css"
    } else if name.ends_with(".woff2") {
        "font/woff2"
    } else if name.ends_with(".png") {
        "image/png"
    } else if name.ends_with(".svg") {
        "image/svg+xml"
    } else {
        "application/octet-stream"
    }
}
